name: Twitter Intelligence
on:
  schedule:
    - cron: '*/10 * * * *' # Alle 10 Minuten
  workflow_dispatch:      # Zum manuellen Testen

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install requests discord-py
      - name: Execute
        env:
          WEBHOOK_LIVE_CHARTS: ${{ secrets.WEBHOOK_LIVE_CHARTS }}
          WEBHOOK_TWITTER_TRADER: ${{ secrets.WEBHOOK_TWITTER_TRADER }}
          WEBHOOK_MARKET_ALERTS: ${{ secrets.WEBHOOK_MARKET_ALERTS }}
        run: python multinews.py
